### ISSUE TITLE
Bug: Travis CI Build-Unknown error

### ISSUE THREAD

**Issue by sidhyatikku** [JBossOutreach/visiting-card-android#136]
#### This issue is about [bug/enhancement] 

- [x] This Bug Fix/Enhancement is worth adding to this repository.
- [x] Issue Title is in form `Bug/Enhancement: Name`.
- [ ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] I will send my PR only after I'm assigned to this issue by any maintainer.
- [ ] I understand that I will be unassigned from this issue if I fail to send a PR for this within a week.

**Actual Behaviour**
The Travis CI is not enabled on this repo. Mentors should enable it by going on dashboard of `travis-ci.org`

**Expected Behaviour**
If linked successfully, travis should then build the android app and update the build status.

**Steps to reproduce it**
Just simply disable travis-ci on this repo.

**Screenshots of the issue**
![screen shot 2018-11-16 at 9 35 10 pm](https://user-images.githubusercontent.com/33092447/48632681-8998a680-e9e7-11e8-8ccf-4483789a1bcf.png)

**Would you like to work on the issue?**
Yes

**System Specifications**
  - Version: -
  - Platform: -
  - Subsystem: -

**Comment by sidhyatikku** [comment]
@SyamSundarKirubakaran @aashutoshrathi @divyanshkul Please look up on this issue.

**Comment by aashutoshrathi** [comment]
Hi, @sidhyatikku 
Thanks for reporting the issue, this is because `.travis.yml` is not parsable.
Travis is enabled since ages :sweat_smile:
